[package]
name = "heroicons"
version = "0.1.0"
edition = "2024"

[dependencies]
hypertext = { version = "~0.12.1", optional = true }

[build-dependencies]
prettyplease = "0.2.37"
proc-macro2 = "1.0.101"
quote = { version = "1.0.40", default-features = false }
syn = "2.0.106"

[features]
hypertext = ["dep:hypertext"]

[package.metadata.docs.rs]
all-features = true
