name: Build, lint, test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build
      run: cargo build
    - name: Run fmt
      run: cargo fmt --check
    - name: Run clippy
      run: cargo clippy -- -Dwarnings
    - name: Run tests
      run: cargo test
